### ISSUE TITLE
Refactor the "Contribute to TiDB" part

### ISSUE THREAD

**Issue by zhangyangyu** [pingcap/tidb-dev-guide#122]
After reading the current "Contribute to TiDB" part, I think it lacks some important information for a common open source development guide:

1. The first thing for an open source development guide is to tell the participants how to behave in the community, they need to follow the CoC.
2. Some missing information includes governance model,  TiDB roadmap, branch strategy, etc.

So I propose to refactor part of the chapters:

- [x] #124
  1. Code of Conduct
  2. Governance
- [x] #126
  1. Checking if an issue already exists
  2. Filing an issue
  3. Making good issues
  4. Understanding the issue’s progress and status
  5. Disagreement With a Resolution on the Issue Tracker
  6. Reporting security vulnerabilities
- [x] #129
  1. TiDB branch strategy
  2. Before contributing
  3. Contributing Process
  4. Writing tests
  5. Making good pull requests
  6. Making good commits
  7. Waiting for review
  8. Following TiDB development
- [x] #131
  1. Principles of the code review
  2. Triaging pull requests
  3. Checking pull requests
  4. Writing code review comments
  5. Accepting pull requests
- [x] #133
  1. Communication channels
  2. Related projects
  3. Community events

Some topics might still remain in discussion so I'll leave over them.

**Comment by xxchan** [comment]
I found there exist [Contribution Guide](https://github.com/pingcap/community/blob/master/contributors/README.md) and [TiDB Community Governance](https://github.com/pingcap/community/blob/master/GOVERNANCE.md) in pingcap/community. Will we link them or maintain both?

**Comment by tisonkun** [comment]
@xxchan I'd prefer we move the content here and let the community repo handle only events, governance details, and votes.

See also https://github.com/pingcap/community/issues/525

**Comment by tisonkun** [comment]
closed as done.
