### ISSUE TITLE
Write down the first version of Code Style and Quality Guide

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb-dev-guide#26]
https://github.com/zz-jason/tidb-dev-guide/edit/master/contribute-to-tidb/code-style-and-quality-guide.md

@gregwebs has several excellent shares offline. I'd like to invite you to enrich this chapter.

**Comment by tisonkun** [comment]
* https://docs.google.com/document/d/1TS-cvAPFwt1yDVhZPFPUulqkqHELE6V9gFzV6jRU77Y
* https://docs.google.com/document/d/1Nq_OvvHYFpayT6o4lIsCgWQ-GRpx4_fYHKIoNGYCJmo

**Comment by tisonkun** [comment]
Hi @gregwebs I can see from the document there are two suggestions valid left

* Modularity and Package size
* Errors with stack traces

Do you plan to add them, too?

**Comment by gregwebs** [comment]
No to packages- too unconventional.

We definitely need a guide to error handling. I am not sure if something like that already exists for TiDB

**Comment by tisonkun** [comment]
IIRC @disking ever wrote [an analyze about pingcap/errors](https://docs.google.com/document/d/12CyoVUwQgIbYHKe5JnYkKzun6mH0dyU1q40UGJDRUDg) (in Chinese, though).

@disking do you know more about if something for error handling already exists for TiDB?

**Comment by djshow832** [comment]
The best practices of reporting errors:
1. The error message should be more user-friendly. Bad case: `The table 101 exceeds table size`. Good case: `The table tbl exceeds table size`.
2. Provide workarounds if necessary. Bad case: `The table tbl exceeds table size`. Good case: `The table tbl exceeds table size. Please try to turn up the value of the system variable tmp_table_size`.
3. Define an error code when it's a general error. Bad case: `The table tbl exceeds table size`. Good case: `Error 1001: The table tbl exceeds table size`.
4. Report the error as early as possible. If you can judge it in the preprocess phase, don't report it in the planner phase. If you can judge it in the planner phase, don't report it in the executor phase. The premise is not breaking the readability and simplicity of the code.

**Comment by tisonkun** [comment]
Thanks for your comments @gregwebs @djshow832 . I think the original issue "Write down the first version of Code Style and Quality Guide" is done since we have rules on this topic. For writing down style guides of error handling. I will create another issue dedicatedly.
