### ISSUE TITLE
transfer this repo to pingcap organization

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb-dev-guide#43]
As planned in [Kick off the TiDB Development Guide](https://internals.tidb.io/t/topic/94), when most of the contents are done, we can request to transfer this repository to pingcap organization to get better maintenance.

Things need to consider:

1. gitbook integration
2. all-contributors integration

**Comment by tisonkun** [comment]
Who is responsible to accept this contribution? That is, who is the man moderates the tranfer.

**Comment by zz-jason** [comment]
I'll send a transfer request, the next step is to wait for the approval of pingcap admins:
<img width="457" alt="Screen Shot 2021-06-29 at 2 50 13 PM" src="https://user-images.githubusercontent.com/5268763/123750591-59c51580-d8e9-11eb-9e06-de82d5a11356.png">
