### ISSUE TITLE
Write down the first version of Privilege Management section of Understanding TiDB

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb-dev-guide#53]
https://github.com/pingcap/tidb-dev-guide/blob/master/src/understand-tidb/privilege-management.md

cc @bb7133 @morgo

**Comment by tisonkun** [comment]
Hi @morgo ! I can see that you contribute a lot on privilege manager functions of TiDB. May you take this section?

**Comment by morgo** [comment]
Sure. You can assign me.

**Comment by tisonkun** [comment]
@morgo thanks for taking over this!
