### ISSUE TITLE
Write down the first version of Session section

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb-dev-guide#54]
https://github.com/pingcap/tidb-dev-guide/blob/master/src/understand-tidb/session.md

cc @bb7133

**Comment by morgo** [comment]
You can assign me

**Comment by tisonkun** [comment]
@morgo thanks for taking over this!

**Comment by tisonkun** [comment]
Hi @morgo you can take a look at the new toc. I regard this section to be "Session" section in the new toc https://github.com/pingcap/tidb-dev-guide/blob/master/src/understand-tidb/session.md

Would you like to schedule a time to finish this section?

**Comment by morgo** [comment]
I will work on this next week. Thanks!

**Comment by tisonkun** [comment]
@morgo thank you!
