### ISSUE TITLE
Write down the first version of Table Statistics section

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb-dev-guide#58]
https://github.com/pingcap/tidb-dev-guide/blob/master/src/understand-tidb/table-statistics.md

cc @yudongusa

**Comment by winoros** [comment]
I'll try to do it this week.

**Comment by tisonkun** [comment]
@winoros Go ahead!

IIUC there are two posts of source code reading series you may make use of 

* https://pingcap.com/blog-cn/tidb-source-code-reading-12
* https://pingcap.com/blog-cn/tidb-source-code-reading-14
