### ISSUE TITLE
Write down the first version of Rule-based Optimization section

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb-dev-guide#59]
We don't have a file for it yet. May we create one on writing.

cc @yudongusa

**Comment by feitian124** [comment]
there are several blogs there such as https://pingcap.com/blog-cn/tidb-source-code-reading-7

**Comment by time-and-fate** [comment]
@tisonkun I'll write for this section. Please assign this to me~

**Comment by tisonkun** [comment]
@time-and-fate done. Thank you!
