### ISSUE TITLE
Write down the first version of The Overview of Transaction section

### ISSUE THREAD

**Issue by you06** [pingcap/tidb-dev-guide#74]
https://github.com/pingcap/tidb-dev-guide/blob/master/src/understand-tidb/transaction.md

**Comment by you06** [comment]
The preset structure requires "Target audience", "What you will learn", and "Small quiz" sections in this file. IMO these sections do not help understand the transaction modules, can we remove them?

Besides, the transaction section may be split into several sub-sections.

Transaction processing

- Optimistic Transaction
- Pessimistic Transaction
- Lock Resolver
- Async Commit
- 1PC

**Comment by tisonkun** [comment]
@you06 thanks for creating this issue.

I agree transaction is a more complex concept and trying to update the toc to reflect it. You can take a look at #76 and add these sections under the transaction section.

**Comment by you06** [comment]
@tisonkun I'll take this issue and add the sub-sections when it's needed.

**Comment by tisonkun** [comment]
> * Optimistic Transaction
> * Pessimistic Transaction
> * Lock Resolver
> * Async Commit
> * 1PC

@you06 shall we simply add these titles as sub sections under "Transaction"?

**Comment by you06** [comment]
This section should be "The Overview of Transaction".
@tisonkun can you help to assign this issue to @cfzjywxk

**Comment by tisonkun** [comment]
@you06 done. Let me update the title, for the content, you can always change on demand.

**Comment by cfzjywxk** [comment]
@you06 
PTAL the overview part.
